#!/usr/bin/env python3
"""Generate wgmma_rs_fp8.cuh: raw-PTX wrappers for Hopper
wgmma.mma_async m64nNk32 f32 += e4m3(A, registers) * e4m3(B, smem desc)
for N in {8,16,...,64}, plus fence/commit/wait helpers and the smem
descriptor builder (128B swizzle, K-major)."""

import sys

NS = [8, 16, 24, 32, 40, 48, 56, 64]
NS_BIG = NS + [96, 128, 192, 256]  # RS/SS e4m3 only (bf16 wrappers stay at N <= 64)

out = []
out.append("// AUTO-GENERATED by gen_wgmma_header.py -- do not edit by hand.")
out.append("#pragma once")
out.append("#include <cstdint>")
out.append("")
out.append("namespace wg {")
out.append("")
out.append(
    '__device__ __forceinline__ void fence() { asm volatile("wgmma.fence.sync.aligned;\\n" ::: "memory"); }'
)
out.append(
    '__device__ __forceinline__ void commit() { asm volatile("wgmma.commit_group.sync.aligned;\\n" ::: "memory"); }'
)
out.append(
    'template <int N> __device__ __forceinline__ void wait() { asm volatile("wgmma.wait_group.sync.aligned %0;\\n" :: "n"(N) : "memory"); }'
)
out.append("")
out.append(
    "// K-major, 128B-swizzled smem tile descriptor: rows of 128 bytes, 8-row atoms"
)
out.append("// of 1024 bytes (SBO=1024), LBO unused for swizzled K-major layouts.")
out.append("__device__ __forceinline__ uint64_t make_desc_sw128(uint32_t smem_addr) {")
out.append("    uint64_t desc = 0;")
out.append(
    "    desc |= (uint64_t)((smem_addr & 0x3FFFF) >> 4);          // start address"
)
out.append(
    "    desc |= (uint64_t)1 << 16;                                // LBO (ignored)"
)
out.append(
    "    desc |= (uint64_t)(1024 >> 4) << 32;                      // SBO = 1024 B"
)
out.append(
    "    desc |= (uint64_t)1 << 62;                                // SWIZZLE_128B"
)
out.append("    return desc;")
out.append("}")
out.append("")
out.append("template <int N> struct MmaRS;")
out.append("")
for n in NS_BIG:
    nregs = n // 2  # 64*N/128 floats per thread
    dlist = ", ".join(f"%{i}" for i in range(nregs))
    a0 = nregs
    alist = ", ".join(f"%{a0 + i}" for i in range(4))
    desc_i = a0 + 4
    scale_i = desc_i + 1
    out.append(f"template <> struct MmaRS<{n}> {{")
    out.append(f"    static constexpr int kRegs = {nregs};")
    out.append(
        f"    // d: {nregs} fp32 accumulators; a: 4 x b32 (16 e4m3); desc_b: smem descriptor; scale_d: 0 -> D = A*B, 1 -> D += A*B"
    )
    out.append(
        f"    __device__ __forceinline__ static void fma(float* d, const uint32_t* a, uint64_t desc_b, int scale_d) {{"
    )
    out.append("        asm volatile(")
    out.append('            "{\\n"')
    out.append('            ".reg .pred p;\\n"')
    out.append(f'            "setp.ne.b32 p, %{scale_i}, 0;\\n"')
    out.append(f'            "wgmma.mma_async.sync.aligned.m64n{n}k32.f32.e4m3.e4m3 "')
    out.append(f'            "{{{dlist}}}, "')
    out.append(f'            "{{{alist}}}, "')
    out.append(f'            "%{desc_i}, p, 1, 1;\\n"')
    out.append('            "}\\n"')
    outs = ", ".join(f'"+f"(d[{i}])' for i in range(nregs))
    out.append(f"            : {outs}")
    out.append(
        '            : "r"(a[0]), "r"(a[1]), "r"(a[2]), "r"(a[3]), "l"(desc_b), "r"(scale_d));'
    )
    out.append("    }")
    out.append("};")
    out.append("")

out.append(
    "// bf16 x bf16 -> f32, m64nNk16, A in registers (4 x b32 = 8 bf16, same fragment layout as the"
)
out.append(
    "// e4m3 k32 variant with 2 elements per register), B K-major in smem (imm-trans-b = 0)."
)
out.append("template <int N> struct MmaRSBF16;")
out.append("")
for n in NS:
    nregs = n // 2
    dlist = ", ".join(f"%{i}" for i in range(nregs))
    a0 = nregs
    alist = ", ".join(f"%{a0 + i}" for i in range(4))
    desc_i = a0 + 4
    scale_i = desc_i + 1
    out.append(f"template <> struct MmaRSBF16<{n}> {{")
    out.append(f"    static constexpr int kRegs = {nregs};")
    out.append(
        f"    __device__ __forceinline__ static void fma(float* d, const uint32_t* a, uint64_t desc_b, int scale_d) {{"
    )
    out.append("        asm volatile(")
    out.append('            "{\\n"')
    out.append('            ".reg .pred p;\\n"')
    out.append(f'            "setp.ne.b32 p, %{scale_i}, 0;\\n"')
    out.append(f'            "wgmma.mma_async.sync.aligned.m64n{n}k16.f32.bf16.bf16 "')
    out.append(f'            "{{{dlist}}}, "')
    out.append(f'            "{{{alist}}}, "')
    out.append(f'            "%{desc_i}, p, 1, 1, 0;\\n"')
    out.append('            "}\\n"')
    outs = ", ".join(f'"+f"(d[{i}])' for i in range(nregs))
    out.append(f"            : {outs}")
    out.append(
        '            : "r"(a[0]), "r"(a[1]), "r"(a[2]), "r"(a[3]), "l"(desc_b), "r"(scale_d));'
    )
    out.append("    }")
    out.append("};")
    out.append("")

out.append("template <int N> struct MmaSS;")
out.append("")
for n in NS_BIG:
    nregs = n // 2
    dlist = ", ".join(f"%{i}" for i in range(nregs))
    da_i = nregs
    db_i = nregs + 1
    scale_i = nregs + 2
    out.append(f"template <> struct MmaSS<{n}> {{")
    out.append(f"    static constexpr int kRegs = {nregs};")
    out.append(
        f"    __device__ __forceinline__ static void fma(float* d, uint64_t desc_a, uint64_t desc_b, int scale_d) {{"
    )
    out.append("        asm volatile(")
    out.append('            "{\\n"')
    out.append('            ".reg .pred p;\\n"')
    out.append(f'            "setp.ne.b32 p, %{scale_i}, 0;\\n"')
    out.append(f'            "wgmma.mma_async.sync.aligned.m64n{n}k32.f32.e4m3.e4m3 "')
    out.append(f'            "{{{dlist}}}, "')
    out.append(f'            "%{da_i}, %{db_i}, p, 1, 1;\\n"')
    out.append('            "}\\n"')
    outs = ", ".join(f'"+f"(d[{i}])' for i in range(nregs))
    out.append(f"            : {outs}")
    out.append('            : "l"(desc_a), "l"(desc_b), "r"(scale_d));')
    out.append("    }")
    out.append("};")
    out.append("")

out.append("}  // namespace wg")
out.append("")

path = sys.argv[1] if len(sys.argv) > 1 else "wgmma_rs_fp8.cuh"
with open(path, "w") as f:
    f.write("\n".join(out))
print("wrote", path)
